// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDolTy9c3NsndP2voUQsM6Q9jhtsk7Js',
    appId: '1:453961147433:web:d27824b2090b0369eba838',
    messagingSenderId: '453961147433',
    projectId: 'flutter-animations-f3d58',
    authDomain: 'flutter-animations-f3d58.firebaseapp.com',
    storageBucket: 'flutter-animations-f3d58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWjsc0akhlBAGcFU3z5SlDyMoZ2D5rVY',
    appId: '1:453961147433:android:0b681e71cba49761eba838',
    messagingSenderId: '453961147433',
    projectId: 'flutter-animations-f3d58',
    storageBucket: 'flutter-animations-f3d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfTrdGIJOkdf0TYey0OGkQL075MOvgYc',
    appId: '1:453961147433:ios:083e3d175a433dd1eba838',
    messagingSenderId: '453961147433',
    projectId: 'flutter-animations-f3d58',
    storageBucket: 'flutter-animations-f3d58.appspot.com',
    iosBundleId: 'com.example.flutterAnimations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjfTrdGIJOkdf0TYey0OGkQL075MOvgYc',
    appId: '1:453961147433:ios:083e3d175a433dd1eba838',
    messagingSenderId: '453961147433',
    projectId: 'flutter-animations-f3d58',
    storageBucket: 'flutter-animations-f3d58.appspot.com',
    iosBundleId: 'com.example.flutterAnimations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDolTy9c3NsndP2voUQsM6Q9jhtsk7Js',
    appId: '1:453961147433:web:c4aab9425f896460eba838',
    messagingSenderId: '453961147433',
    projectId: 'flutter-animations-f3d58',
    authDomain: 'flutter-animations-f3d58.firebaseapp.com',
    storageBucket: 'flutter-animations-f3d58.appspot.com',
  );
}
