import 'package:flutter_animations/live_score/models/team/team.dart';
import 'package:flutter_animations/live_score/models/player.dart';

Team buildHomeTeam() {
  return Team(
      name: 'Inter',
      players: [
        Player(
            shirtNumber: 1,
            playerName: 'Sommer',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 28,
            playerName: 'Pavard',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 15,
            playerName: 'Acerbi',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 95,
            playerName: 'Bastoni',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 32,
            playerName: 'Di Marco',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 22,
            playerName: 'Mkhitaryan',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 20,
            playerName: 'Calhanoglu',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 23,
            playerName: 'Barella',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 36,
            playerName: 'Darmian',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 9,
            playerName: 'Thuram',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 10,
            playerName: 'Lautaro',
            isAHomeTeamPlayer: true,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
      ],
      iconPath:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/512px-FC_Internazionale_Milano_2021.svg.png');
}

Team buildAwayTeam() {
  return Team(
      name: 'Napoli',
      players: [
        Player(
            shirtNumber: 1,
            playerName: 'Meret',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 22,
            playerName: 'Di Lorenzo',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 13,
            playerName: 'Rrahmani',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 5,
            playerName: 'Jesus',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 6,
            playerName: 'M. Rui',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 99,
            playerName: 'Anguissa',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 68,
            playerName: 'Lobotka',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 8,
            playerName: 'Traorè',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 21,
            playerName: 'Politano',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 9,
            playerName: 'Osimhen',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
        Player(
            shirtNumber: 81,
            playerName: 'Raspadori',
            isAHomeTeamPlayer: false,
            isCautioned: false,
            isExpelled: false,
            hasScored: false,
            numberOfGoals: 0),
      ],
      iconPath: 'assets/images/n_logo.png');
}
